// packages/super-app-ng/src/app/app.component.ts
import { Component } from '@angular/core';

@Component({
  selector: 'ds-root',
  template: `<div>
    <h1>Hello, to my cool design system!</h1>

    <ds-button
      type="button"
      size="pluto"
      variant="primary"
      (click)="handleClick()"
      (customover)="handleHover()"
      >Click me</ds-button
    >
  </div>`,
  styles: [''],
})
export class AppComponent {
  handleClick() {
    alert('Hey, I clicked my button!');
  }

  handleHover() {
    console.log('Hey, hover of my button!');
  }
}

// packages/super-app-react/src/app/app.tsx
// eslint-disable-next-line @typescript-eslint/no-unused-vars
import { Button } from '@ds/beauty-react';

export function App() {
  return (
    <>
      <h1>Hello, to my cool design system!</h1>

      <Button
        type="button"
        size="medium"
        onclick={e => {
          alert('Hey, I clicked my button!');
        }}
        oncustomover={e => {
          console.log('Hey, hover of my button!');
        }}
      >
        Click me
      </Button>
    </>
  );
}

export default App;
